spring.application.name=database_migration

spring.datasource.url=jdbc:mysql://localhost:3306/libraryProject
spring.datasource.username=libraryAdmin
spring.datasource.password=libraryAdmin@password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379